### PR TITLE
:recycle: remove firefox interval hack

### PR DESCRIPTION
**Pull request by IanVS**
Fixes https://github.com/leonardodino/rci/issues/10 (kind of)

This removes the setInterval for firefox, since it does not appear to be needed since firefox 55.  I would suggest that if users need to support versions older than that, they can use something like https://github.com/2is10/selectionchange-polyfill.  But calling a function every 16ms seems like overkill and a good way to drain batteries.  I could be wrong about this, but it worked correctly in my version of firefox (95) in local testing.

I also updated the codesandbox slightly to fix an annoying chrome behavior, in which nothing appeared to be focused after resetting the input following an error.  Maybe there's a better way to do that, but I couldn't find one.

### CODE REVIEW

**Comment by IanVS** [comment]
I see you have a new PR with a more elegant way to change the selection.  Is the Firefox change here worth considering?  If so, I will remove the other commit.

**Comment by IanVS** [comment]
@leonardodino what do you think about removing the firefox `setInterval`?

**Comment by leonardodino** [comment]
wow, great news! 🙌 

When I first wrote this code, for a personal project ~1-2 years ago, it was needed. Even though Firefox had this event for a long while, it wasn't as precise as webkit/chromium, so it wasn't working for this use case, hence the interval hack 😅 

I just updated my firefox install again to test it, and has since been fixed! 
~6months ago, in firefox 92: https://bugzilla.mozilla.org/show_bug.cgi?id=1648944

**Comment by leonardodino** [comment]
I've reverted the chrome that was in this PR, in favour of the one merged in #13
thanks for fixing this! 🙌

**Pull request merged**
