### PR TITLE
:sparkles: calculate ideal input width

### LINKED ISSUE #16: Underlying input width
Hey, first off thank you so much for the library - I appreciate how much effort has gone into the a11y complexities of this design pattern.

Currently the underlying `<input>` has an inline style with `width: 200%` - and this is not overridable with the `inputStyle` class as it's defined after the spread of `inputStyle`.

I noticed that when using a password manager like 1Password, it causes the little 1Password icon to appear quite far off where the dummy input appears visually:

image

I can override the `input` width by smacking a `!important` on my own defined class e.g. `width: 120% !important,` but before I commit to this solution do I risk breaking something that I'm not aware of? It seems okay so far, but just want to double check.

Cheers!

### PR DESCRIPTION
**Pull request by jasikpark**
fixes #16

### CODE REVIEW

**Comment by leonardodino** [comment]
hey, sorry for the delay, I might have some time to check this over the weekend.
I agree that this needs to be fixed, password managers are a good thing and should be supported.

regarding the code:
the backticks on this line might be a good indication that this used to be calculated, I don't remember exactly.
I ended up putting `200%` in the end as a failsafe for other designs, as it's quite tricky.
from memory, one of the hard things to test is iOS especially when unfocusing+focusing an input that is filled, didn't found a reliable way to e2e test that.

now that we have `padding`+`spacing` props (original private implementation didn't had those, relied only on `flex`, sound nice but had corner-cases) it might be possible again to calculate some sane value, but we need to ensure doesn't break other cases. (120% might break for inputs of lenght < 4, for example)

thanks for taking the time for triaging issues and contributing PRs here! 💯🙌

**Comment by leonardodino** [comment]
hopefully fixed now! 🙌 

what I did: add the equivalent of another segment at the end.

Screenshot 2022-05-09 at 21 02 02

(should be enough for 99% of cases, otherwise the user can pass `inputWidth` prop to fine-tune it)

**Comment by leonardodino** [comment]
✨  just published `rci@0.0.2` with this change! ✨ 
cc: @hwhmeikle

(also contains a new prop on `CodeInput` and `RCI.Input` to accept width, so no css hackery is needed)

**Comment by hwhmeikle** [comment]
Thanks so much everyone!

**Comment by jasikpark** [comment]
awesome! thanks for sorting that out :)

hopefully someone running into an edgecase will find this pr as docs :p

**Pull request merged**
